FROM flyvoly/intel-nuc-lomp-base:latest

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/app
COPY ./src ./src
COPY entrypoint.sh .
RUN /bin/bash -c "source /opt/ros/melodic/setup.sh; catkin build -j4 mavlink spinnaker_sdk_camera_driver px4 mavlink_sitl_gazebo mavros mavros_extras volys_precision_landing robot_localization px4 image_proc"

RUN ["chmod", "+x", "/usr/app/entrypoint.sh"]
ENTRYPOINT ["/usr/app/entrypoint.sh"]