FROM flyvoly/intel-nuc-lomp-base:latest

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/app
COPY ./src ./src
COPY entrypoint.sh .
RUN /bin/bash -c "source /opt/ros/melodic/setup.sh; catkin build -j4 mavlink spinnaker_sdk_camera_driver mavros mavros_extras volys_precision_landing robot_localization image_proc"

RUN ["chmod", "+x", "/usr/app/entrypoint.sh"]
ENTRYPOINT ["/usr/app/entrypoint.sh"]