version: 2.1
jobs:
  build-ros-ws:
    docker:
      - image: flyvoly/lomp:latest

    resource_class: medium

    steps:
      - checkout
      - run:
          name: Setup submodules
          command: git submodule sync --recursive && git submodule update --init --recursive
      - run:
          name: Build ros packages
          command: catkin build px4 mavlink_sitl_gazebo volys_precision_landing

workflows:
  version: 2

  build-workflow:
    jobs: 
      - build-ros-ws
