version: 2.1
jobs:
  build-ros-ws:
    docker:
      - image: flyvoly/lomp:latest

    resource_class: medium

    steps:
      - checkout
      - run:
          name: Setup submodules
          command: |
            chmod 700 .ssh/key
            eval `ssh-agent`
            ssh-add .ssh/key
            git submodule sync --recursive && git submodule update --init --recursive
      - run:
          name: Build ros packages
          command: |
            source /opt/ros/melodic/setup.bash
            catkin build -j4 px4 mavlink_sitl_gazebo mavros mavros_extras volys_precision_landing robot_localization
      - save_cache:
          key: precision-landing-{{ .Branch }}-{{ .Revision }}
          paths: 
            - ./

  run-precision-landing-test:
    docker:
      - image: flyvoly/lomp:latest

    resource_class: large
    
    steps:
      - restore_cache:
          keys: 
            - precision-landing-{{ .Branch }}-{{ .Revision }}
      
      - run:
          name: Run VTOL Mission
          command: |
            export SITL_RUN_SH="/root/project/src/px4_firmware/test/rostest_precision_landing.sh"
            echo ${SITL_RUN_SH}
            bash ${SITL_RUN_SH} precision_landing_test.test

  run-precision-landing-payload-drop-test:
    docker:
      - image: flyvoly/lomp:latest

    resource_class: large
    
    steps:
      - restore_cache:
          keys: 
            - precision-landing-{{ .Branch }}-{{ .Revision }}
      
      - run:
          name: Run VTOL Mission
          command: |
            export SITL_RUN_SH="/root/project/src/px4_firmware/test/rostest_precision_landing.sh"
            echo ${SITL_RUN_SH}
            bash ${SITL_RUN_SH} precision_landing_payload_drop.test

workflows:
  version: 2

  precision-landing-test:
    jobs: 
      - build-ros-ws
      - run-precision-landing-test:
          requires:
            - build-ros-ws
      - run-precision-landing-payload-drop-test:
          requires:
            - build-ros-ws

  
