/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file skypower_status.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT skypower_status_s {
#else
struct skypower_status_s {
#endif
	uint64_t timestamp;
	uint32_t rev_counter;
	float operating_time_s;
	uint16_t engine_speed;
	uint16_t engine_target_load;
	uint16_t engine_current_load;
	uint16_t engine_current_torque;
	uint16_t engine_current_power;
	uint16_t maximum_load;
	uint16_t injection_fuel_flow;
	uint16_t specific_fuel_consumption;
	uint16_t injection_valve_load;
	uint16_t red_factor;
	int16_t engine_temp_1;
	int16_t engine_temp_2;
	int16_t exhaust_temp_1;
	int16_t exhaust_temp_2;
	int16_t msl_engine_temp_1;
	int16_t msl_engine_temp_2;
	int16_t msl_exhaust_temp_1;
	int16_t msl_exhaust_temp_2;
	int16_t air_temp;
	int16_t ecu_temp;
	uint16_t current_altitude;
	uint16_t isa_altitude;
	uint16_t density_altitude;
	uint16_t pressure_altitude;
	uint16_t ambient_pressure_hpa;
	uint16_t sfc_map;
	uint16_t fuel_flow_icao;
	uint16_t torque_icao;
	uint16_t power_icao;
	int16_t ignition_angle;
	uint16_t throttle_angle;
	int16_t ignition_gap;
	uint16_t injection_angle;
	uint16_t injection_time;
	uint16_t sensor_error_flags;
	uint16_t thermal_limit_flags;
	uint16_t eng_supply_voltage;
	int16_t gen_motor_speed;
	int16_t gen_current_output;
	int16_t gen_phase_current;
	uint16_t gen_supply_voltage;
	uint16_t gen_bridge_voltage;
	int16_t gen_battery_current;
	int16_t gen_temp;
	int16_t gen_controller_temp;
	uint8_t _padding0[6]; // required for logger


#ifdef __cplusplus

#endif
};

/* register this as object request broker structure */
ORB_DECLARE(skypower_status);


#ifdef __cplusplus
void print_message(const skypower_status_s& message);
#endif
